In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('http://dados.ufrn.br/dataset/8bf1a468-48ff-4f4d-95ee-b17b7a3a5592/resource/ff0a457e-76fa-4aca-ad99-48aebd7db070/download/docentes.csv', sep=';')

In [4]:
df.head()

,siape,nome,sexo,formacao,tipo_jornada_trabalho,vinculo,categoria,classe_funcional,id_unidade_lotacao,lotacao,admissao
0,349938,GILDETE AZEVEDO,F,DESCONHECIDA,Dedicação exclusiva,Ativo Permanente,PROFESSOR DE 1 E 2 GRAUS,C ...,1452,NÚCLEO DE EDUCAÇÃO DA INFÂNCIA,1984/08/27 00:00:00.000000000
1,1543339,ADELE GUIMARAES UBARANA SANTOS,F,MESTRADO,Dedicação exclusiva,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,DIII ...,1452,NÚCLEO DE EDUCAÇÃO DA INFÂNCIA,2006/07/24 00:00:00.000000000
2,1554468,AFRANIO CESAR DE ARAUJO,M,DOUTORADO,Dedicação exclusiva,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,DIV ...,351,ESCOLA AGRÍCOLA DE JUNDIAÍ,2008/09/12 00:00:00.000000000
3,1177821,AIRTON FERNANDES GUIMARAES FILHO,M,MESTRADO,Dedicação exclusiva,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,DIII ...,284,ESCOLA DE MÚSICA,1998/04/28 00:00:00.000000000
4,2360824,ALDAIR RODRIGUES DA SILVA,M,MESTRADO,Dedicação exclusiva,Ativo Permanente,PROFESSOR DE ENSINO BASICO TECNICO E TECNOLOGICO,DIII ...,351,ESCOLA AGRÍCOLA DE JUNDIAÍ,2017/01/25 00:00:00.000000000

In [5]:
#modifica direto na tabela
df.drop('nome', axis=1, inplace=True)

In [6]:
df.describe(include='object')

,sexo,formacao,tipo_jornada_trabalho,vinculo,categoria,classe_funcional,lotacao,admissao
count,2396,2396,2396,2396,2396,2396,2396,2396
unique,3,5,3,1,3,13,107,1151
top,M,DOUTORADO,Dedicação exclusiva,Ativo Permanente,PROFESSOR DO MAGISTERIO SUPERIOR,Classe D - Associado ...,ESCOLA AGRÍCOLA DE JUNDIAÍ,2009/01/27 00:00:00.000000000
freq,1332,1998,2110,2396,2187,822,105,84

In [7]:
df.sexo.unique()

array(['F', 'M', 'false'], dtype=object)

In [8]:
lotacoes = df.lotacao.unique()

In [9]:
totalPorLotacao = []
for lot in lotacoes:
    totalPorLotacao.append(df['lotacao'].where(df['lotacao'] == lot).count())
#print(totalPorLotacao)

In [10]:
dfl = pd.DataFrame({
    'lotacao': lotacoes,
    'total': totalPorLotacao
})
dfl

                                               lotacao  total
0                       NÚCLEO DE EDUCAÇÃO DA INFÂNCIA     45
1                           ESCOLA AGRÍCOLA DE JUNDIAÍ    105
2                                     ESCOLA DE MÚSICA     61
3                          INSTITUTO METROPOLE DIGITAL     48
4                                      ESCOLA DE SAÚDE     40
..                                                 ...    ...
102                    SUPERINTENDENCIA DE COMUNICACAO      1
103           CERES - DEPTO CIÊNCIAS SOCIAIS E HUMANAS      1
104             SECRETARIA DE GOVERNANÇA INSTITUCIONAL      1
105                  SUPERINTENDÊNCIA DO HUOL - EBSERH      1
106  PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIA E ENGENHA...      1

[107 rows x 2 columns]

In [11]:
dfl.sort_values(by=['total'], ascending=False)

                                               lotacao  total
1                           ESCOLA AGRÍCOLA DE JUNDIAÍ    105
14                     ESCOLA DE CIÊNCIAS E TECNOLOGIA     94
24   FACULDADE DE CIÊNCIAS DA SAÚDE DO TRAIRI - FACISA     74
2                                     ESCOLA DE MÚSICA     61
13   ESCOLA MULTICAMPI DE CIÊNCIAS MÉDICAS DO RIO G...     58
..                                                 ...    ...
94                                  GABINETE DO REITOR      1
5                                EDITORA UNIVERSITÁRIA      1
7                   SECRETARIA DE EDUCAÇÃO A DISTÂNCIA      1
57                    COORDENAÇÃO DO CURSO DE FARMÁCIA      1
106  PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIA E ENGENHA...      1

[107 rows x 2 columns]

In [15]:
for lot in lotacoes:
    tf = (df['sexo']).where((df['sexo'] == 'F') & (df['lotacao'] == lot)).count()
    tm = (df['sexo']).where((df['sexo'] == 'M') & (df['lotacao'] == lot)).count()
    tfgb = tf/(tf+tm)*100
    tmgb = tm/(tf+tm)*100
    print(lot)
    print("F: " + str(tfgb) + "%")
    print("M: " + str(tmgb) + "%\n")
    #print(tf)
    #print(tm)

NÚCLEO DE EDUCAÇÃO DA INFÂNCIA
F: 93.33333333333333%
M: 6.666666666666667%

ESCOLA AGRÍCOLA DE JUNDIAÍ
F: 38.095238095238095%
M: 61.904761904761905%

ESCOLA DE MÚSICA
F: 26.229508196721312%
M: 73.77049180327869%

INSTITUTO METROPOLE DIGITAL
F: 20.833333333333336%
M: 79.16666666666666%

ESCOLA DE SAÚDE
F: 90.0%
M: 10.0%

EDITORA UNIVERSITÁRIA
F: 100.0%
M: 0.0%

PRÓ-REITORIA DE EXTENSÃO UNIVERSITÁRIA
F: 50.0%
M: 50.0%

SECRETARIA DE EDUCAÇÃO A DISTÂNCIA
F: 100.0%
M: 0.0%

DEPARTAMENTO DE ENGENHARIA ELÉTRICA
F: 4.545454545454546%
M: 95.45454545454545%

CERES - DEPARTAMENTO DE HISTÓRIA
F: 40.0%
M: 60.0%

DEPARTAMENTO DE PEDIATRIA
F: 73.33333333333333%
M: 26.666666666666668%

DEPARTAMENTO DE ENGENHARIA CIVIL
F: 41.30434782608695%
M: 58.69565217391305%

DEPARTAMENTO DE ENGENHARIA DE COMUNICACOES
F: 7.142857142857142%
M: 92.85714285714286%

ESCOLA MULTICAMPI DE CIÊNCIAS MÉDICAS DO RIO GRANDE DO NORTE
F: 51.724137931034484%
M: 48.275862068965516%

ESCOLA DE CIÊNCIAS E TECNOLOGIA
F: 29.78723404255319%
M: 70.2127659574468%

DEPARTAMENTO DE ENGENHARIA DE COMPUTACAO E AUTOMACAO
F: 0.0%
M: 100.0%

INSTITUTO DE QUÍMICA
F: 35.08771929824561%
M: 64.91228070175438%

DEPARTAMENTO DE GEOFÍSICA
F: 9.090909090909092%
M: 90.9090909090909%

DEPARTAMENTO DE CIÊNCIAS CONTÁBEIS - DCC
F: 31.25%
M: 68.75%

DEPARTAMENTO DE ENGENHARIA MECANICA
F: 0.0%
M: 100.0%

DEPARTAMENTO DE FUNDAMENTOS E POLÍTICAS DA EDUCAÇÃO
F: 72.97297297297297%
M: 27.027027027027028%

DEPARTAMENTO DE FARMACIA
F: 34.375%
M: 65.625%

DEPARTAMENTO DE ANÁLISES CLÍNICAS E TOXICOLÓGICAS
F: 59.09090909090909%
M: 40.909090909090914%

DEPARTAMENTO DE ODONTOLOGIA
F: 56.60377358490566%
M: 43.39622641509434%

FACULDADE DE CIÊNCIAS DA SAÚDE DO TRAIRI - FACISA
F: 70.27027027027027%
M: 29.72972972972973%

DEPARTAMENTO DE BIOLOGIA CELULAR E GENÉTICA
F: 66.66666666666666%
M: 33.33333333333333%

DEPARTAMENTO DE LINGUAS E LITERATURAS ESTRANGEIRAS MODERNAS
F: 51.85185185185185%
M: 48.148148148148145%

DEPARTAMENTO DE ECOLOGIA
F: 53.333333333333336%
M: 46.666666666666664%

DEPARTAMENTO DE BOTÂNICA E ZOOLOGIA
F: 35.714285714285715%
M: 64.28571428571429%

DEPARTAMENTO DE COMPUTAÇÃO E TECNOLOGIA
F: 16.666666666666664%
M: 83.33333333333334%

INSTITUTO DO CÉREBRO
F: 22.22222222222222%
M: 77.77777777777779%

DEPARTAMENTO DE COMUNICAÇÃO SOCIAL
F: 36.11111111111111%
M: 63.888888888888886%

DEPARTAMENTO DE MEDICINA CLÍNICA
F: 56.75675675675676%
M: 43.24324324324324%

DEPARTAMENTO DE FÍSICA TEÓRICA E EXPERIMENTAL
F: 13.157894736842104%
M: 86.8421052631579%

DEPARTAMENTO DE ENGENHARIA DE PETROLEO
F: 18.75%
M: 81.25%

DEPARTAMENTO DE GEOGRAFIA/CCHLA
F: 28.57142857142857%
M: 71.42857142857143%

DEPARTAMENTO DE ARTES
F: 60.0%
M: 40.0%

CERES - DEPTO CIÊNCIAS EXATAS E APLICADAS
F: 25.0%
M: 75.0%

DEPARTAMENTO DE MATEMÁTICA
F: 22.727272727272727%
M: 77.27272727272727%

DEPARTAMENTO DE TOCO-GINECOLOGIA
F: 50.0%
M: 50.0%

DEPARTAMENTO DE CIÊNCIAS ADMINISTRATIVAS - DEPAD
F: 38.46153846153847%
M: 61.53846153846154%

DEPARTAMENTO DE EDUCAÇÃO FÍSICA
F: 29.411764705882355%
M: 70.58823529411765%

DEPARTAMENTO DE POLÍTICAS PÚBLICAS
F: 60.0%
M: 40.0%

EBSERH - GERÊNCIA DE ENSINO E PESQUISA
F: 16.666666666666664%
M: 83.33333333333334%

DEPARTAMENTO DE ARQUITETURA
F: 54.83870967741935%
M: 45.16129032258064%

DEPARTAMENTO DE LETRAS
F: 51.02040816326531%
M: 48.97959183673469%

DEPARTAMENTO DE PRÁTICAS EDUCACIONAIS E CURRÍCULO
F: 59.523809523809526%
M: 40.476190476190474%

DEPARTAMENTO DE EDUCAÇÃO - CERES
F: 73.33333333333333%
M: 26.666666666666668%

DEPARTAMENTO DE BIOFÍSICA E FARMACOLOGIA
F: 41.17647058823529%
M: 58.82352941176471%

DEPARTAMENTO DE CIRURGIA
F: 17.647058823529413%
M: 82.35294117647058%

FACULDADE DE ENGENHARIA, LETRAS E CIÊNCIAS SOCIAIS DO SERIDÓ - FELCS
F: 48.64864864864865%
M: 51.35135135135135%

DEPARTAMENTO DE GEOLOGIA
F: 20.0%
M: 80.0%

DEPARTAMENTO DE ENFERMAGEM
F: 88.09523809523809%
M: 11.904761904761903%

INSTITUTO HUMANITAS DE ESTUDOS INTEGRADOS
F: 12.5%
M: 87.5%

DEPARTAMENTO DE MORFOLOGIA
F: 50.0%
M: 50.0%

DEPARTAMENTO DE ECONOMIA - DEPEC
F: 50.0%
M: 50.0%

DEPARTAMENTO DE FISIOTERAPIA
F: 69.44444444444444%
M: 30.555555555555557%

COORDENAÇÃO DO CURSO DE FARMÁCIA
F: 100.0%
M: 0.0%

DEPARTAMENTO DE ADMINISTRAÇÃO PUBLICA E GESTÃO SOCIAL
F: 46.15384615384615%
M: 53.84615384615385%

DEPARTAMENTO DE DIREITO PRIVADO - DIPRI
F: 36.36363636363637%
M: 63.63636363636363%

DEPARTAMENTO DE FISIOLOGIA E COMPORTAMENTO
F: 68.42105263157895%
M: 31.57894736842105%

DEPARTAMENTO DE PSICOLOGIA
F: 64.0%
M: 36.0%

MUSEU CÂMARA CASCUDO
F: 66.66666666666666%
M: 33.33333333333333%

DEPARTAMENTO DE ANTROPOLOGIA
F: 71.42857142857143%
M: 28.57142857142857%

DEPARTAMENTO DE NUTRIÇÃO
F: 96.55172413793103%
M: 3.4482758620689653%

DEPARTAMENTO DE FONOAUDIOLOGIA
F: 88.23529411764706%
M: 11.76470588235294%

DEPARTAMENTO DE MICROBIOLOGIA E PARASITOLOGIA
F: 72.0%
M: 28.000000000000004%

DEPARTAMENTO DE CIÊNCIAS SOCIAIS
F: 35.714285714285715%
M: 64.28571428571429%

DEPARTAMENTO DE ENGENHARIA DE MATERIAIS
F: 20.0%
M: 80.0%

DEPARTAMENTO DE SAÚDE COLETIVA
F: 66.66666666666666%
M: 33.33333333333333%

DEPARTAMENTO DE SERVIÇO SOCIAL - DESSO
F: 80.95238095238095%
M: 19.047619047619047%

DEPARTAMENTO DE ENGENHARIA QUIMICA
F: 50.0%
M: 50.0%

DEPARTAMENTO DE CIÊNCIA DA INFORMAÇÃO
F: 75.0%
M: 25.0%

DEPARTAMENTO DE TURISMO - DETUR
F: 47.05882352941176%
M: 52.94117647058824%

DEPARTAMENTO DE DIREITO PUBLICO - DIPUB
F: 29.411764705882355%
M: 70.58823529411765%

DEPARTAMENTO DE INFECTOLOGIA
F: 60.0%
M: 40.0%

DEPARTAMENTO DE MEDICINA INTEGRADA
F: 20.454545454545457%
M: 79.54545454545455%

DEPARTAMENTO DE ESTATISTICA
F: 35.0%
M: 65.0%

DEPARTAMENTO DE INFORMÁTICA E MATEMÁTICA APLICADA
F: 25.71428571428571%
M: 74.28571428571429%

DEPARTAMENTO DE OCEANOGRAFIA E LIMNOLOGIA
F: 38.46153846153847%
M: 61.53846153846154%

DEPARTAMENTO DE DIREITO - CERES
F: 9.090909090909092%
M: 90.9090909090909%

DEPARTAMENTO DE FILOSOFIA
F: 23.809523809523807%
M: 76.19047619047619%

DEPARTAMENTO DE ENGENHARIA PRODUÇÃO
F: 36.84210526315789%
M: 63.1578947368421%

DEPARTAMENTO DE ENGENHARIA BIOMEDICA
F: 50.0%
M: 50.0%

DEPARTAMENTO DE CIÊNCIAS ATMOSFÉRICAS E CLIMÁTICAS
F: 16.666666666666664%
M: 83.33333333333334%

EBSERH - DIVISÃO DE APOIO DIAGNOSTICO E TERAPEUTICO
F: 0.0%
M: 100.0%

DEPARTAMENTO DE BIOQUÍMICA
F: 47.05882352941176%
M: 52.94117647058824%

DEPARTAMENTO DE DIREITO PROCESSUAL E PROPEDÊUTICA - DEPRO
F: 5.555555555555555%
M: 94.44444444444444%

DEPARTAMENTO DE HISTÓRIA
F: 48.0%
M: 52.0%

DEPARTAMENTO DE PATOLOGIA
F: 42.857142857142854%
M: 57.14285714285714%

DEPARTAMENTO DE ENGENHARIA TÊXTIL
F: 37.5%
M: 62.5%

DEPARTAMENTO DE DEMOGRAFIA E CIENCIAS ATUARIAIS
F: 36.36363636363637%
M: 63.63636363636363%

CERES - DEPARTAMENTO DE GEOGRAFIA
F: 25.0%
M: 75.0%

DEPARTAMENTO DE DESIGN
F: 36.36363636363637%
M: 63.63636363636363%

GABINETE DO REITOR
F: 0.0%
M: 100.0%

ADMINISTRAÇÃO DO NUCLEO DE MACAU
F: 0.0%
M: 100.0%

PRÓ-REITORIA DE ADMINISTRAÇÃO (PROAD)
F: 100.0%
M: 0.0%

INSTITUTO DE MEDICINA TROPICAL - IMT-RN
F: 0.0%
M: 100.0%

UNIVERSIDADE FEDERAL DO RIO GRANDE DO NORTE
F: 0.0%
M: 100.0%

EBSERH - DIVISÃO DE GESTÃO DE CUIDADO
F: 33.33333333333333%
M: 66.66666666666666%

DIREÇÃO DO NUCLEO DE NOVA CRUZ
F: 0.0%
M: 100.0%

COORDENAÇÃO DO CURSO DE FÍSICA - A DISTÂNCIA
F: 0.0%
M: 100.0%

SUPERINTENDENCIA DE COMUNICACAO
F: 100.0%
M: 0.0%

CERES - DEPTO CIÊNCIAS SOCIAIS E HUMANAS
F: 100.0%
M: 0.0%

SECRETARIA DE GOVERNANÇA INSTITUCIONAL
F: 0.0%
M: 100.0%

SUPERINTENDÊNCIA DO HUOL - EBSERH
F: 0.0%
M: 100.0%

PROGRAMA DE PÓS-GRADUAÇÃO EM CIÊNCIA E ENGENHARIA DE MATERIAIS
F: 0.0%
M: 100.0%

In [13]:
#dfl2 = pd.DataFrame({
#    'lotacao': lotacoes,
#    'F': tf,
#    'M': tm,
#    'total': totalPorLotacao
#})
#dfl2